name: Test Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-

      - name: Remove cached config.json
        run: rm -f src/main/resources/config.json
        shell: bash

      - name: Update remoteRun value to 'true' in config.json file
        run: |
          sed -i 's/"remoteRun": false/"remoteRun": true/g' src/main/resources/config.json
        shell: bash

      - name: Verify remoteRun value
        run:
          grep '"remoteRun": true' src/main/resources/config.json
        shell: bash

      - name: Build with Maven
        run: mvn -B clean package

      - name: Run UI tests
        run: mvn test
