name: Test Pipeline

on:
  workflow_dispatch:

jobs:
  ui-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Install Google Chrome
        run: choco install googlechrome -y
        shell: pwsh

      - name: Install Chrome WebDriver
        run: choco install chromedriver -y
        shell: pwsh

      - name: Run UI tests
        run: mvn clean test
        continue-on-error: true

      - name: Generate Allure report
        if: always()
        run: mvn allure:report

      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/allure-report

      - name: Upload test reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
