name: Test Pipeline

on:
  workflow_dispatch:

jobs:
  ui-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Install Google Chrome
        run: choco install googlechrome -y
        shell: pwsh
      
      - name: Install Chrome WebDriver
        run: choco install chromedriver -y
        shell: pwsh

      - name: Run UI tests
        run: mvn test
