name: Test Pipeline

on:
  workflow_dispatch:

jobs:
    ui-test:
      runs-on: windows-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up JDK 17
          uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Run tests
          run: mvn clean test

        - name: Generate Allure Report
          if: always()
          run: mvn allure:report

        - name: Upload Allure Report
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: allure-report
            path: target/site/allure-report

        - name: Upload Log Files
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: log-files
            path: logs/

        - name: Upload Surefire Reports
          if: failure()
          uses: actions/upload-artifact@v3
          with:
            name: surefire-reports
            path: target/surefire-reports/

        - name: Display Allure Report Info
          run: echo "Allure Report uploaded. To view it, download the 'allure-report' artifact and open its index.html file in your browser."
